-- CREATE SCHEMA

CREATE SCHEMA IF NOT EXISTS slotify
				DEFAULT CHARACTER SET utf8;

USE slotify;

-- CREATE USERS TABLE

CREATE TABLE IF NOT EXISTS users (
	user_id		INTEGER			NOT NULL		AUTO_INCREMENT PRIMARY KEY,
	username	VARCHAR(25)		NOT NULL,
	first_name	VARCHAR(25)		NOT NULL,
	last_name	VARCHAR(25)		NOT NULL,
	email		VARCHAR(200)	NOT NULL,
	password	VARCHAR(32)		NOT NULL,
	created_date	DATETIME	NOT NULL	DEFAULT NOW(),
	updated_date	DATETIME	NOT NULL	DEFAULT NOW() ON UPDATE NOW(),
	profile_pic		VARCHAR(500)
);
